closedverse/urls.py
from django.conf.urls import url, include

from django.contrib import admin
from .settings import INSTALLED_APPS

handler500 = 'closedverse_main.views.server_err'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^', include('closedverse_main.urls'))
]

if 'silk' in INSTALLED_APPS:
	urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]

closedverse_main/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from django.shortcuts import redirect

from . import views
from closedverse.settings import MEDIA_URL, MEDIA_ROOT 

username = r'(?P<username>[A-Za-z0-9-\'-._ ]+)'
community = r'(?P<community>[0-9]+)'
post = r'(?P<post>[0-9]+)'
comment = r'(?P<comment>[0-9]+)'
uuidr = r'[0-9a-f\-]'

app_name = 'main'

urlpatterns = [
	# Root
	url(r'^^$|^communities$|^index.*$$', views.community_list, name='community-list'),
	# Accounts
	url(r'login/$', views.login_page, name='login'),
	url(r'signup/$', views.signup_page, name='signup'),
	url(r'reset/$', views.forgot_passwd, name='forgot-passwd'),
	url(r'logout/$', views.logout_page, name='logout'),
	# User pages
	url(r'users/'+ username +'/manager$', views.user_manager, name='user-manager'),
	url(r'users/'+ username +'/follow$', views.user_follow, name='user-follow'),
	url(r'users/'+ username +'/unfollow$', views.user_unfollow, name='user-unfollow'),
	url(r'users/'+ username +'$', views.user_view, name='user-view'),
	url(r'users/'+ username +'/posts$', views.user_posts, name='user-posts'),
	url(r'users/'+ username +'/yeahs$', views.user_yeahs, name='user-yeahs'),
	url(r'users/'+ username +'/comments$', views.user_comments, name='user-comments'),
	url(r'users/'+ username +'/following$', views.user_following, name='user-following'),
	url(r'users/'+ username +'/followers$', views.user_followers, name='user-followers'),
	url(r'users/'+ username +'/friends$', views.user_friends, name='user-friends'),
	# User page friends
	url(r'users/'+ username +'/friend_new$', views.user_friendrequest_create, name='user-fr-create'),
	url(r'users/'+ username +'/friend_accept$', views.user_friendrequest_accept, name='user-fr-accept'),
	url(r'users/'+ username +'/friend_reject$', views.user_friendrequest_reject, name='user-fr-reject'),
	url(r'users/'+ username +'/friend_cancel$', views.user_friendrequest_cancel, name='user-fr-cancel'),
	url(r'users/'+ username +'/friend_delete$', views.user_friendrequest_delete, name='user-fr-delete'),
	
	url(r'users/'+ username +'/block$', views.user_addblock, name='user-addblock'),
	# Communities
	url(r'communities.search$', views.community_search, name='community-search'),
	url(r'communities/'+ community +'$', views.community_view, name='community-view'),
	url(r'communities/favorites$', views.community_favorites, name='community-favorites'),
	url(r'communities/all$', views.community_all, name='community-viewall'),
	url(r'communities/(?P<tag>[a-z]+)$', views.special_community_tag, name='special-community-tag'),
	url(r'communities/'+ community +'/favorite$', views.community_favorite_create, name='community-favorite-add'),
	url(r'communities/'+ community +'/favorite_rm$', views.community_favorite_rm, name='community-favorite-rm'),
	url(r'communities/'+ community +'/posts$', views.post_create, name='post-create'),
	# Posts and comments
	# Some of these NAMES (not patterns) are hardcoded into models.py
	url(r'posts/'+ post +'$', views.post_view, name='post-view'),
	url(r'posts/'+ post +'/yeah$', views.post_add_yeah, name='post-add-yeah'),
	url(r'posts/'+ post +'/yeahu$', views.post_delete_yeah, name='post-delete-yeah'),
	url(r'posts/'+ post +'/comments$', views.post_comments, name='post-comments'),
	url(r'posts/'+ post +'/comments$', views.post_comments, name='post-comments'),
	url(r'posts/'+ post +'/change$', views.post_change, name='post-change'),
	url(r'posts/'+ post +'/profile$', views.post_setprofile, name='post-set-profile'),
	url(r'posts/'+ post +'/profile_rm', views.post_unsetprofile, name='post-unset-profile'),
	url(r'posts/'+ post +'\.rm$', views.post_rm, name='post-rm'),
	url(r'comments/'+ comment +'$', views.comment_view, name='comment-view'),
	url(r'comments/'+ comment +'/yeah$', views.comment_add_yeah, name='comment-add-yeah'),
	url(r'comments/'+ comment +'/yeahu$', views.comment_delete_yeah, name='comment-delete-yeah'),
	url(r'comments/'+ comment +'/change$', views.comment_change, name='comment-change'),
	url(r'comments/'+ comment +'/rm$', views.comment_rm, name='comment-rm'),
	# Post-meta: polls
	url(r'poll/(?P<poll>'+ uuidr +'+)/vote$', views.poll_vote, name='poll-vote'),
	url(r'poll/(?P<poll>'+ uuidr +'+)/unvote$', views.poll_unvote, name='poll-unvote'),
	
	# Notifications
	url(r'alive$', views.check_notifications, name='check-notifications'),
	url(r'notifications/?$', views.notifications, name='notifications'),
	url(r'notifications/friend_requests/?$', views.friend_requests, name='friend-requests'),
	url(r'notifications/set_read$', views.notification_setread, name='set-read'),
	url(r'notifications/(?P<notification>'+ uuidr +'+)\.rm$', views.notification_delete, name='notification-delete'),
	
	# User meta + messages
	url(r'activity/?$', views.activity_feed, name='activity'),
	url(r'users.search$', views.user_search, name='user-search'),
	url(r'pref$', views.prefs, name='prefs'),
	url(r'settings/profile$', views.profile_settings, name='profile-settings'),
	url(r'messages/?$', views.messages, name='messages'),
	url(r'messages/(?P<message>'+ uuidr +'+)/rm$', views.message_rm, name='message-delete'),
	url(r'messages/'+ username +'$', views.messages_view, name='messages-view'),
	url(r'messages/'+ username +'/read$', views.messages_read, name='messages-read'),
	
	# Help/configuration
	url(r'lights$', views.set_lighting, name='set-lighting'),
	url(r'complaints$', views.help_complaint, name='complaints'),
	url(r'server$', views.server_stat, name='server-stat'),
	url(r'help/rules/?$', views.help_rules, name='help-rules'),
	url(r'help/faq/?$', views.help_faq, name='help-faq'),
	url(r'help/legal/?$', views.help_legal, name='help-legal'),
	url(r'help/contact/?$', views.help_contact, name='help-contact'),
	url(r'help/login/?$', views.help_login, name='help-login'),
	url(r'why/?$', views.help_why, name='help-why'),
	
	# Manage
	url(r'man/?$', views.admin_index, name='admin-index'),
	url(r'man/users$', views.admin_users, name='admin-users'),
	url(r'man/users_list$', views.users_list, name='users-list'),
	
	
	# "API"
	url(r'posts.json$', views.post_list, name='post-list'),
	
	# Util, right now we are away from the primary appo
	url(r'origin$', views.origin_id, name='origin-id-get'),
	# :^)
	#url(r'openverse.png', views.openverse_logo, name='openverse-logo'),
	url(r'debug$', lambda request: redirect('https://youtu.be/dQw4w9WgXcQ'), name='rickroll'),

] + static(MEDIA_URL, document_root=MEDIA_ROOT)

closedverse_main/views.py
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseBadRequest,  HttpResponseServerError, HttpResponseForbidden, JsonResponse
from django.template import loader
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.core.validators import EmailValidator
from django.core.exceptions import ValidationError
from django.db.models import Q, Count, Exists, OuterRef
from .models import *
from .util import *
from .serializers import CommunitySerializer
from closedverse import settings
import re
from django.urls import reverse
from random import getrandbits
from random import choice
from json import dumps, loads
import sys, traceback
from subprocess import Popen, PIPE
from datetime import datetime
import django.utils.dateformat
from binascii import hexlify
from os import urandom

#from silk.profiling.profiler import silk_profile

def json_response(msg='', code=0, httperr=400):
	thing = {
	# success would be false, but 0 is faster I think (Miiverse used 0 because Perl doesn't have bools)
	# it also should be removed
	'success': 0,
	'errors': [
			{
			# We should drop this Miiverse formatting at some point
			'message': msg,
			'error_code': code,
			}
		],
	'code': httperr,
	}
	return JsonResponse(thing, safe=False, status=httperr)

def community_list(request):
	"""Lists communities / main page."""
	if 'json' in request.META.get('HTTP_ACCEPT', ''):
		cs = CommunitySerializer
		response = {
			'general': cs.many(Community.objects.filter(type=0).order_by('-created')),
			'game': cs.many(Community.objects.filter(type=1).order_by('-created')),
			'special': cs.many(Community.objects.filter(type=2).order_by('-created'))
		}
		return JsonResponse(response)
	obj = Community.objects
	if request.user.is_authenticated:
		classes = ['guest-top']
		favorites = request.user.community_favorites()
	else:
		classes = []
		favorites = None
	return render(request, 'closedverse_main/community_list.html', {
		'title': 'Communities',
		'classes': classes,
		'general': obj.filter(type=0).order_by('-created')[0:8],
		'game': obj.filter(type=1).order_by('-created')[0:8],
		'special': obj.filter(type=2).order_by('-created')[0:8],
		'feature': obj.filter(is_feature=True).order_by('-created'),
		'favorites': favorites,
		'settings': settings,
		'ogdata': {
				'title': 'Community List',
				'description': "Openverse is a social network: designed by PF2M, programmed by Arian Kordi. With Miiverse DNA, style and familiar assets such as Miiverse's interface and Miis, you're sure to have fun here!",
				'date': 'None',
				'image': request.build_absolute_uri(settings.STATIC_URL + 'img/favicon.png'),
			},
	})
def community_all(request):
	"""All communities, with pagination"""
	try:
		offset = int(request.GET.get('offset', '0'))
	except ValueError:
		offset = 0
	if request.user.is_authenticated:
		classes = ['guest-top']
	else:
		classes = []
	gen = Community.get_all(0, offset)
	game = Community.get_all(1, offset)
	special = Community.get_all(2, offset)
	if gen.count() > 11 or game.count() > 11 or special.count() > 11:
		has_next = True
	else:
		has_next = False
	if gen.count() < 1 or game.count() < 1:
		has_back = True
	else:
		has_back = False
	back = offset - 12
	next = offset + 12
	return render(request, 'closedverse_main/community_all.html', {
		'title': 'All Communities',
		'classes': classes,
		'general': gen,
		'game': game,
		'special': special,
		'has_next': has_next,
		'next': next,
	})

def community_search(request):
	"""Community searching"""
	query = request.GET.get('query')
	if not query or len(query) < 2:
		raise Http404()
	if request.GET.get('offset'):
		communities = Community.search(query, 20, int(request.GET['offset']), request)
	else:
		communities = Community.search(query, 20, 0, request)
	if communities.count() > 19:
		if request.GET.get('offset'):
			next_offset = int(request.GET['offset']) + 20
		else:
			next_offset = 20
	else:
		next_offset = None
	return render(request, 'closedverse_main/community-search.html', {
		'classes': ['search'],
		'query': query,
		'communities': communities,
		'next': next_offset,
	})

@login_required
def community_favorites(request):
	"""Favorite communities, can be used for self by default or other users"""
	user = request.user
	has_other = False
	if request.GET.get('u'):
		user = get_object_or_404(User, username=request.GET['u'])
		has_other = True
		profile = user.profile()
		profile.setup(request)
		communities = user.community_favorites(True)
	else:
		communities = request.user.community_favorites(True)
		profile = user.profile()
		profile.setup(request)
	return render(request, 'closedverse_main/community_favorites.html', {
		'title': 'Favorite communities',
		'favorites': communities,
		'user': user,
		'profile': profile,
		'other': has_other,
	})

def login_page(request):
	"""Login page! using our own user objects."""
	# Redirect the user to / if they're logged in, forcing them to log out
	if request.user.is_authenticated:
		return redirect('/')
	if request.method == 'POST':
		# If we don't have all of the POST parameters we want..
		if not (request.POST['username'] and request.POST['password']): 
		# then return that.
			return HttpResponseBadRequest("You didn't fill in all of the fields.")
		# Now let's authenticate.
		# Wait, first check if the user exists. Remove spaces from the username, because some people do that.
		# Hold up, first we need to check proxe.
		# Never mind
		"""
		if settings.PROD:
			if iphub(request.META['REMOTE_ADDR']):
				spamuser = True
				if settings.disallow_proxy:
					# This was for me, a server error will email admins of course.
					raise ValueError
		"""
		user = User.objects.authenticate(username=request.POST['username'], password=request.POST['password'])
		# None = doesn't exist, False = invalid password.
		if user is None:
			return HttpResponseNotFound("The user doesn't exist.")
		else:
			# Todo: I might want to do some things relating to making models take care of object stuff like this instead of the view, it's totally messed up now.
			successful = False if user[1] is False or not user[0].is_active() else True
			LoginAttempt.objects.create(user=user[0], success=successful, addr=request.META.get('REMOTE_ADDR'))
			if user[1] is False:
				return HttpResponse("Invalid password.", status=401)
			elif user[1] is 2:
				return HttpResponse("This account's password needs to be reset. Contact an admin or reset by email.", status=400)
			elif not user[0].is_active():
				return HttpResponseForbidden("This account was disabled.")
		request.session['passwd'] = user[0].password
		login(request, user[0])
		
		# Then, let's get the referrer and either return that or the root.
		# Actually, let's not for now.
		#if request.META['HTTP_REFERER'] and "login" not in request.META['HTTP_REFERER'] and request.META['HTTP_HOST'] in request.META['HTTP_REFERER']:
		#	location = request.META['HTTP_REFERER']
		#else:
		location = '/'
		if request.GET.get('next'):
			location = request.GET['next']
		return HttpResponse(location)
	else:
		return render(request, 'closedverse_main/login_page.html', {
			'title': 'Log in',
			#'classes': ['no-login-btn']
		})
def signup_page(request):
	"""Signup page, lots of checks here"""
	# Redirect the user to / if they're logged in, forcing them to log out
	if request.user.is_authenticated:
		return redirect('/')
	if request.method == 'POST':
		if settings.recaptcha_pub:
			if not recaptcha_verify(request, settings.recaptcha_priv):
				return HttpResponse("The reCAPTCHA validation has failed.", status=402)
		if not (request.POST.get('username') and request.POST.get('password') and request.POST.get('password_again')):
			return HttpResponseBadRequest("You didn't fill in all of the required fields.")
		if not re.compile(r'^[A-Za-z0-9-._]{1,32}$').match(request.POST['username']) or not re.compile(r'[A-Za-z0-9]').match(request.POST['username']):
			return HttpResponseBadRequest("Your username either contains invalid characters or is too long (only letters + numbers, dashes, dots and underscores are allowed")
		if settings.PROD:
			for keyword in ['admin', 'admln', 'adrnin', 'admn', ]:
				if keyword in request.POST['username'].lower():
					return HttpResponseForbidden("You aren't funny. Please use a funny name.")
		conflicting_user = User.objects.filter(Q(username__iexact=request.POST['username']) | Q(username__iexact=request.POST['username'].replace(' ', '')))
		if conflicting_user:
			return HttpResponseBadRequest("A user with that username already exists.")
		if not request.POST['password'] == request.POST['password_again']:
			return HttpResponseBadRequest("Your passwords don't match.")
		if not (request.POST['nickname'] or request.POST['origin_id']):
			return HttpResponseBadRequest("You didn't fill in an NNID, so you need a nickname.")
		if request.POST['nickname'] and len(request.POST['nickname']) > 32:
			return HttpResponseBadRequest("Your nickname is either too long or too short (1-32 characters)")
		if request.POST['origin_id'] and (len(request.POST['origin_id']) > 16 or len(request.POST['origin_id']) < 6):
			return HttpResponseBadRequest("The NNID provided is either too short or too long.")
		if request.POST.get('email'):
			if User.email_in_use(request.POST['email']):
				return HttpResponseBadRequest("That email address is already in use, that can't happen.")
			try:
				EmailValidator()(value=request.POST['email'])
			except ValidationError:
				return HttpResponseBadRequest("Your e-mail address is invalid. Input an e-mail address, or input nothing.")
		check_others = Profile.objects.filter(user__addr=request.META['REMOTE_ADDR'], let_freedom=False).exists()
		if check_others:

closedverse_main/templates/closedverse_main/man/admin-user-list.html
{% load closedverse_user %}{% load closedverse_tags %}<div class="list follow-list">
  <ul class="list-content-with-icon-and-text arrow-list" id="user-man-list" data-next-page-url="{% if next %}/users.html?o={{ next }}{% endif %}">
  {% for user in users %}
  <li class="trigger" data-href="{% url "main:user-view" user.username %}" data-action="{% url "main:user-manager" user.username %}">
    {% user_icon_container user 0 %}

	<div class="toggle-button">
      	<button type="button" class="button user-manage symbol">Manage</button>
	</div>

  <div class="body">
    <p class="title">
      <span class="nick-name"><a href="{% url "main:user-view" user.username %}">{{ user.nickname }}</a></span>
      <span class="id-name">{{ user.username }}</span>
    </p>
    <p class="text">{{ user.profile.comment }}</p>

  </div>
</li>
  {% endfor %}
  </ul>
</div>

closedverse_main/templates/closedverse_main/man/main.html
{% extends "closedverse_main/layout.html" %}
{% block main-body %}{% load closedverse_user %}{% load closedverse_tags %}
{% user_sidebar request user user.profile 0 True %}
<div class="main-column"><div class="post-list-outline">
<h2 class="label">{{ title }}</h2>
<div class="setting-form">
<ul class="settings-list">
	<h2 class="label">Management pages</h2>
      <li class="setting-userman-go">
        <p class="settings-label"><h3>User management</h3>
		<br>Delete (new) users, disable people, see email addresses, change username, give profile editing restriction</p>
			<button class="button" data-href="{% url "main:admin-users" %}">Go</button>
      </li>
	  <br>That's it for now
	  <!--
	  <li class="setting-userman-go">
        <p class="settings-label"><h3>Server management</h3>
		<br>Force logins, enable account approval.</p>
			<br>Todo
      </li>
	  <li class="setting-userman-go">
        <p class="settings-label"><h3>Images view</h3>
		<br>Look at images posted on this server to identify bad activity, trace back, and delete.</p>
			<br>Todo
      </li>
	  <li class="setting-userman-go">
        <p class="settings-label"><h3>Audit log</h3>
		<br>It's an audit log.</p>
			<br>Todo
      </li>
	  -->
	<h2 class="label">Bulk deletion stuff (janky, more or less temporary)</h2>
      <li class="setting-pruge1">
        <p class="settings-label">Purge ALL yeahs + yeah notifications by a user (permanent)</p>
		<form>
			<div class="center center-input">
				<input type="hidden" name="action" value="purge1">
				<input type="text" name="username" maxlength="32" placeholder="Username" value="">
			</div>
			<button class="button">Do it</button>
		</form>
      </li>
      <li class="setting-pruge2">
        <p class="settings-label">Purge ALL posts + comments by a user (recoverable)</p>
		<form>
			<div class="center center-input">
				<input type="hidden" name="action" value="purge2">
				<input type="text" name="username" maxlength="32" placeholder="Username" value="">
			</div>
			<button class="button">Do it</button>
		</form>
      </li>
      <li class="setting-pruge3">
        <p class="settings-label">Delete all of a user's friendships and messages</p>
		<form>
			<div class="center center-input">
				<input type="hidden" name="action" value="purge3">
				<input type="text" name="username" maxlength="32" placeholder="Username" value="">
			</div>
			<button class="button">Do it</button>
		</form>
      </li>
      <li class="setting-pruge4">
        <p class="settings-label">Delete a user's following list</p>
		<form>
			<div class="center center-input">
				<input type="hidden" name="action" value="purge4">
				<input type="text" name="username" maxlength="32" placeholder="Username" value="">
			</div>
			<button class="button">Do it</button>
		</form>
      </li>
      <li class="setting-pruge5">
        <p class="settings-label">Rename a user, change their avatar, and don't let them change it back to something else</p>
		<form>
			<div class="center center-input">
				<input type="hidden" name="action" value="purge5">
				<input type="text" name="username" maxlength="32" placeholder="Username" value="">
			</div>
			<button class="button">Do it</button>
		</form>
      </li>
      <li class="setting-unpurge1">
        <p class="settings-label">Undelete a user's posts/comments, make them able to change their avatar</p>
		<form>
			<div class="center center-input">
				<input type="hidden" name="action" value="unpurge1">
				<input type="text" name="username" maxlength="32" placeholder="Username" value="">
			</div>
			<button class="button">Do it</button>
		</form>
      </li>


</ul></div></div></div>
{% endblock %}

closedverse_main/templates/closedverse_main/man/users.html
{% extends "closedverse_main/layout.html" %}
{% block main-body %}{% load closedverse_tags %}{% load closedverse_user %}
{% user_sidebar request user user.profile 0 True %}
<div class="main-column">
<div class="post-list-outline">
    <h2 class="label">Manage users</h2>
	<div class="user-loads">
		{% discordapp_spinner %}
		<br>
	</div>
        
  </div>
</div>
<div id="user-man-template" class="dialog none" data-is-template="1">
<div class="dialog-inner">
  <div class="window">
    <h1 class="window-title"></h1>
    <div class="window-body">
		<div class="user-info"></div>
        <form class="goodform">
			<div class="center-input">
				<input type="text" name="username" placeholder="Username" value=""><br>
				<input type="text" name="email" placeholder="E-mail" value=""><br>
				<input type="text" name="addr" placeholder="Addr" value=""><br>
			</div>
			<br>
			<input type="checkbox" name="active" value="1"> Is active<br>
        <div class="form-buttons">
          <input type="button" class="olv-modal-close-button gray-button" value="Close">
          <input type="submit" class="post-button black-button" value="Save">
        </div>
      </form>
    </div>
  </div>
</div>
</div>
{% endblock %}